### PR TITLE
Merge test branch to upstream

### PR DESCRIPTION
**Pull request by Y-T-G**

### CODE REVIEW

**Comment by PythonLimited** [comment]
hm i merged it anyway :D 
do you want to continue the kernel on your own or can i merge them from time to time?

**Comment by Y-T-G** [comment]
No problem if you wish to merge them. I will be uploading builds to XDA.

**Comment by PythonLimited** [comment]
Ok. Kernel or Rom builds?

**Comment by Y-T-G** [comment]
Kernel

**Comment by PythonLimited** [comment]
Another question. Are you good in upgrading kernels?
I want to do LOS 15.1 but unfortunately the kernel still hangs at some stage and gives null pointer references. I think it's the stuff from qpnp-sec-charger and thermal due to which I had to enable alarmtimer and partially rewrite alarmtimer and hrtimer. So I want to rewrite everything from scratch again but help is really needed  i mean it's a one man project currently.
Also this conversation kinda sucks as it's very slow.
Can you send me a Mail with some messengers you (may) using?
Leonardomeitz@gmail.com bis my mail

**Comment by Y-T-G** [comment]
Sorry, I wish I could help. But I am more of copy-paster now than an actual dev. I am actually in the group NeoHomies. User: iFiLaMeNe

**Pull request closed without merging**
